export const ITENS = 'ITENS';
export const PAGE = 'PAGE';
export const LOGIN = 'LOGIN';
export const SET_INITIALS_STATE = 'SET_INITIALS_STATE';
export const GET_CURRENCY_CONVERTED = 'GET_CURRENCY_CONVERTED';
export const GET_CURRENCY_CONVERTED_SUCCESS = 'GET_CURRENCY_CONVERTED_SUCCESS';
