const currency = [
    {name: "AED", title: "United Arab Emirates Dirham"},
    {name: "AFN", title: "Afghan Afghani"},
    {name: "ALL", title: "Albanian Lek"},
    {name: "AMD", title: "Armenian Dram"},
    {name: "ANG", title: "Dutch Guilders"},
    {name: "AOA", title: "Angolan Kwanza"},
    {name: "ARS", title: "Argentine Peso"},
    {name: "AUD", title: "Australian Dollar"},
    {name: "AWG", title: "Aruban Florin"},
    {name: "AZN", title: "Azerbaijani Manat"},
    {name: "BAM", title: "Bosnia-Herzegovina Convertible Mark"},
    {name: "BBD", title: "Barbadian Dollar"},
    {name: "BDT", title: "Bangladeshi Taka"},
    {name: "BGN", title: "Bulgarian Lev"},
    {name: "BHD", title: "Bahraini Dinar"},
    {name: "BIF", title: "Burundian Franc"},
    {name: "BMD", title: "Bermudian Dollar"},
    {name: "BND", title: "Bruneian Dollar"},
    {name: "BOB", title: "Bolivian Boliviano"},
    {name: "BRL", title: "Brazilian Real"},
    {name: "BSD", title: "Bahamian Dollar"},
    {name: "BTN", title: "Bhutanese Ngultrum"},
    {name: "BWP", title: "Botswanan Pula"},
    {name: "BZD", title: "Belizean Dollar"},
    {name: "CAD", title: "Canadian Dollar"},
    {name: "CDF", title: "Congolese Franc"},
    {name: "CHF", title: "Swiss Franc"},
    {name: "CLF", title: "Chilean Unit of Account UF"},
    {name: "CLP", title: "Chilean Peso"},
    {name: "CNH", title: "Chinese Yuan Offshore"},
    {name: "CNY", title: "Chinese Yuan"},
    {name: "COP", title: "Colombian Peso"},
    {name: "CUP", title: "Cuban Peso"},
    {name: "CVE", title: "Cape Verdean Escudo"},
    {name: "CZK", title: "Czech Republic Koruna"},
    {name: "DJF", title: "Djiboutian Franc"},
    {name: "DKK", title: "Danish Krone"},
    {name: "DOP", title: "Dominican Peso"},
    {name: "DZD", title: "Algerian Dinar"},
    {name: "EGP", title: "Egyptian Pound"},
    {name: "ERN", title: "Eritrean Nakfa"},
    {name: "ETB", title: "Ethiopian Birr"},
    {name: "EUR", title: "Euro"},
    {name: "FJD", title: "Fijian Dollar"},
    {name: "FKP", title: "Falkland Islands Pound"},
    {name: "GBP", title: "British Pound Sterling"},
    {name: "GEL", title: "Georgian Lari"},
    {name: "GHS", title: "Ghanaian Cedi"},
    {name: "GIP", title: "Gibraltar Pound"},
    {name: "GMD", title: "Gambian Dalasi"},
    {name: "GNF", title: "Guinean Franc"},
    {name: "GTQ", title: "Guatemalan Quetzal"},
    {name: "GYD", title: "Guyanaese Dollar"},
    {name: "HKD", title: "Hong Kong Dollar"},
    {name: "HNL", title: "Honduran Lempira"},
    {name: "HRK", title: "Croatian Kuna"},
    {name: "HTG", title: "Haitian Gourde"},
    {name: "HUF", title: "Hungarian Forint"},
    {name: "IDR", title: "Indonesian Rupiah"},
    {name: "ILS", title: "Israeli New Sheqel"},
    {name: "INR", title: "Indian Rupee"},
    {name: "IQD", title: "Iraqi Dinar"},
    {name: "IRR", title: "Iranian Rial"},
    {name: "ISK", title: "Icelandic Krona"},
    {name: "JMD", title: "Jamaican Dollar"},
    {name: "JOD", title: "Jordanian Dinar"},
    {name: "JPY", title: "Japanese Yen"},
    {name: "KES", title: "Kenyan Shilling"},
    {name: "KGS", title: "Kyrgystani Som"},
    {name: "KHR", title: "Cambodian Riel"},
    {name: "KMF", title: "Comorian Franc"},
    {name: "KPW", title: "North Korean Won"},
    {name: "KRW", title: "South Korean Won"},
    {name: "KWD", title: "Kuwaiti Dinar"},
    {name: "KYD", title: "Caymanian Dollar"},
    {name: "KZT", title: "Kazakhstani Tenge"},
    {name: "LAK", title: "Laotian Kip"},
    {name: "LBP", title: "Lebanese Pound"},
    {name: "LKR", title: "Sri Lankan Rupee"},
    {name: "LRD", title: "Liberian Dollar"},
    {name: "LSL", title: "Basotho Maloti"},
    {name: "LYD", title: "Libyan Dinar"},
    {name: "MAD", title: "Moroccan Dirham"},
    {name: "MDL", title: "Moldovan Leu"},
    {name: "MGA", title: "Malagasy Ariary"},
    {name: "MKD", title: "Macedonian Denar"},
    {name: "MMK", title: "Myanma Kyat"},
    {name: "MNT", title: "Mongolian Tugrik"},
    {name: "MOP", title: "Macanese Pataca"},
    {name: "MRU", title: "Mauritanian Ouguiya (1973–2017)"},
    {name: "MUR", title: "Mauritian Rupee"},
    {name: "MVR", title: "Maldivian Rufiyaa"},
    {name: "MWK", title: "Malawian Kwacha"},
    {name: "MXN", title: "Mexican Peso"},
    {name: "MYR", title: "Malaysian Ringgit"},
    {name: "MZN", title: "Mozambican Metical"},
    {name: "NAD", title: "Namibian Dollar"},
    {name: "NGN", title: "Nigerian Naira"},
    {name: "NOK", title: "Norwegian Krone"},
    {name: "NPR", title: "Nepalese Rupee"},
    {name: "NZD", title: "New Zealand Dollar"},
    {name: "OMR", title: "Omani Rial"},
    {name: "PAB", title: "Panamanian Balboa"},
    {name: "PEN", title: "Peruvian Nuevo Sol"},
    {name: "PGK", title: "Papua New Guinean Kina"},
    {name: "PHP", title: "Philippine Peso"},
    {name: "PKR", title: "Pakistani Rupee"},
    {name: "PLN", title: "Polish Zloty"},
    {name: "PYG", title: "Paraguayan Guarani"},
    {name: "QAR", title: "Qatari Rial"},
    {name: "RON", title: "Romanian Leu"},
    {name: "RSD", title: "Serbian Dinar"},
    {name: "RUB", title: "Russian Ruble"},
    {name: "RWF", title: "Rwandan Franc"},
    {name: "SAR", title: "Saudi Arabian Riyal"},
    {name: "SCR", title: "Seychellois Rupee"},
    {name: "SDG", title: "Sudanese Pound"},
    {name: "SEK", title: "Swedish Krona"},
    {name: "SGD", title: "Singapore Dollar"},
    {name: "SHP", title: "Saint Helena Pound"},
    {name: "SLL", title: "Sierra Leonean Leone"},
    {name: "SOS", title: "Somali Shilling"},
    {name: "SRD", title: "Surinamese Dollar"},
    {name: "SYP", title: "Syrian Pound"},
    {name: "SZL", title: "Swazi Emalangeni"},
    {name: "THB", title: "Thai Baht"},
    {name: "TJS", title: "Tajikistani Somoni"},
    {name: "TMT", title: "Turkmenistani Manat"},
    {name: "TND", title: "Tunisian Dinar"},
    {name: "TOP", title: "Tongan Pa'anga"},
    {name: "TRY", title: "Turkish Lira"},
    {name: "TTD", title: "Trinidad and Tobago Dollar"},
    {name: "TWD", title: "Taiwan New Dollar"},
    {name: "TZS", title: "Tanzanian Shilling"},
    {name: "UAH", title: "Ukrainian Hryvnia"},
    {name: "UGX", title: "Ugandan Shilling"},
    {name: "USD", title: "United States Dollar"},
    {name: "UYU", title: "Uruguayan Peso"},
    {name: "UZS", title: "Uzbekistan Som"},
    {name: "VND", title: "Vietnamese Dong"},
    {name: "VUV", title: "Ni-Vanuatu Vatu"},
    {name: "WST", title: "Samoan Tala"},
    {name: "XAF", title: "CFA Franc BEAC"},
    {name: "XCD", title: "East Caribbean Dollar"},
    {name: "XDR", title: "Special Drawing Rights"},
    {name: "XOF", title: "CFA Franc BCEAO"},
    {name: "XPF", title: "CFP Franc"},
    {name: "YER", title: "Yemeni Rial"},
    {name: "ZAR", title: "South African Rand"},
    {name: "ZMW", title: "Zambian Kwacha"}
  // {name:"usd"},
    // {name:"brl"},
    // {name:"eur"},
    // {name:"gbp"},
    // {name:"aud"},
    // {name:"cad"},
    // {name:"jpy"},
    // {name:"chf"},
    // {name:"pab"},
    // {name:"sbd"},
    // {name:"mwk"},
    // {name:"gtq"},
    // {name:"bwp"},
    // {name:"rub"},
    // {name:"idr"},
    // {name:"bhd"},
    // {name:"uah"},
    // {name:"lbp"},
    // {name:"gmd"},
    // {name:"bif"},
    // {name:"mmk"},
    // {name:"lkr"},
    // {name:"clp"},
    // {name:"sek"},
    // {name:"php"},
    // {name:"mro"},
    // {name:"gel"},
    // {name:"bsd"},
    // {name:"gnf"},
    // {name:"sll"},
    // {name:"scr"},
    // {name:"dkk"},
    // {name:"aed"},
    // {name:"twd"},
    // {name:"jod"},
    // {name:"uyu"},
    // {name:"gyd"},
    // {name:"rwf"},
    // {name:"mzn"},
    // {name:"tzs"},
    // {name:"cny"},
    // {name:"kwd"},
    // {name:"huf"},
    // {name:"ngn"},
    // {name:"amd"},
    // {name:"crc"},
    // {name:"nad"},
    // {name:"syp"},
    // {name:"top"},
    // {name:"mnt"},
    // {name:"nzd"},
    // {name:"hrk"},
    // {name:"byn"},
    // {name:"mdl"},
    // {name:"mga"},
    // {name:"xcd"},
    // {name:"lak"},
    // {name:"cup"},
    // {name:"sar"},
    // {name:"hkd"},
    // {name:"qar"},
    // {name:"uzs"},
    // {name:"iqd"},
    // {name:"svc"},
    // {name:"awg"},
    // {name:"aoa"},
    // {name:"khr"},
    // {name:"zar"},
    // {name:"mxn"},
    // {name:"lyd"},
    // {name:"rsd"},
    // {name:"stn"},
    // {name:"djf"},
    // {name:"hnl"},
    // {name:"npr"},
    // {name:"czk"},
    // {name:"thb"},
    // {name:"xof"},
    // {name:"egp"},
    // {name:"pyg"},
    // {name:"fjd"},
    // {name:"cdf"},
    // {name:"lsl"},
    // {name:"sos"},
    // {name:"krw"},
    // {name:"bgn"},
    // {name:"pgk"},
    // {name:"azn"},
    // {name:"bob"},
    // {name:"lrd"},
    // {name:"sdg"},
    // {name:"mru"},
    // {name:"wst"},
    // {name:"mur"},
    // {name:"isk"},
    // {name:"pkr"},
    // {name:"kgs"},
    // {name:"afn"},
    // {name:"ttd"},
    // {name:"ang"},
    // {name:"dop"},
    // {name:"bam"},
    // {name:"dzd"},
    // {name:"pln"},
    // {name:"gip"},
    // {name:"tmt"},
    // {name:"etb"},
    // {name:"cve"},
    // {name:"zmw"},
    // {name:"yer"},
    // {name:"bnd"},
    // {name:"sgd"},
    // {name:"ils"},
    // {name:"tnd"},
    // {name:"irr"},
    // {name:"ghs"},
    // {name:"mkd"},
    // {name:"xpf"},
    // {name:"all"},
    // {name:"mvr"},
    // {name:"cop"},
    // {name:"xaf"},
    // {name:"omr"},
    // {name:"ars"},
    // {name:"bzd"},
    // {name:"kmf"},
    // {name:"szl"},
    // {name:"kes"},
    // {name:"inr"},
    // {name:"bbd"},
    // {name:"vnd"},
    // {name:"mad"},
    // {name:"ves"},
    // {name:"jmd"},
    // {name:"ssp"},
    // {name:"ern"},
    // {name:"ugx"},
    // {name:"myr"},
    // {name:"ron"},
    // {name:"pen"},
    // {name:"kzt"},
    // {name:"nio"},
    // {name:"srd"},
    // {name:"htg"},
    // {name:"mop"},
    // {name:"vuv"},
    // {name:"nok"},
    // {name:"try"},
    // {name:"bdt"},
    // {name:"tjs"}
  ]
  
  export default currency 